name: apk_kesehatan
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  pdf: ^3.10.7
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/consultation_icon.png
    - assets/information_icon.png
    - assets/legal_icon.png
    - assets/home_icon.png
    - assets/profile_picture.jpg
    - assets/checkup_icon.png
    - assets/telemedicine_icon.png
    - assets/carousel_image1.jpg
    - assets/carousel_image2.jpg
    - assets/carousel_image3.jpg